services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--api.insecure=true" # Enables web UI
      - "--providers.docker=true" # Enabling Docker as provider
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false" # Do not expose containers by default unless explicitly specified
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=poshakajay@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8082"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # for web UI
      - "8082:8082" # for metrics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - app-network-prod

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - GO_ENV=production
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb-prod:27017/${MONGODB_DATABASE}?authSource=${MONGODB_DATABASE}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports:
      - "8095:8095"
    labels:
      - "traefik.enable=true" # Explicitly telling Traefik to expose this container
      - "traefik.http.routers.app-prod.entrypoints=websecure" # Allow requests from predefined entrypoint named "websecure"
      - "traefik.http.routers.app-prod.rule=Host(`urlly.app`)"
      - "traefik.http.routers.app-prod.tls.certresolver=myresolver"

    depends_on:
      - mongodb-prod
    networks:
      - app-network-prod
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      driver: loki
      options:
        loki-url: "http://172.31.16.214:3100/loki/api/v1/push"
        loki-external-labels: service=url-shortener

  mongodb-prod:
    image: mongo:6
    command: mongod --auth --quiet
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}

    volumes:
      - mongodb-data-prod:/data/db
      - ${PWD}/init-scripts:/docker-entrypoint-initdb.d:Z
    networks:
      - app-network-prod
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 4G
    ulimits:
      nproc: 64000
      nofile:
        soft: 64000
        hard: 64000

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    ports:
      - "9100:9100"
    labels:
      app: "url-shortener"
      environment: "production"

volumes:
  mongodb-data-prod:

networks:
  app-network-prod:
    driver: bridge
